export interface Location {
  slug: string;
  city: string;
  country: string;
  flag: string;
  region: "Europe" | "North America" | "Oceania" | "UK" | "Middle East";
  currency: "EUR" | "USD" | "GBP" | "CAD" | "AUD" | "AED";
  currencySymbol: string;
  timezone: string; // e.g., "CET", "EST"
  minRate: number; // minimum project size in that currency
  avgSalary: number; // yearly senior dev salary
  overheadCost: number; // estimate of taxes + benefits + office
  hiringDifficulty: "Medium" | "High" | "Extremely High";
}

export const locations: Location[] = [
  {
    slug: "berlin",
    city: "Berlin",
    country: "Germany",
    flag: "🇩🇪",
    region: "Europe",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "CET",
    minRate: 2000,
    avgSalary: 95000,
    overheadCost: 25000,
    hiringDifficulty: "High",
  },
  {
    slug: "london",
    city: "London",
    country: "United Kingdom",
    flag: "🇬🇧",
    region: "UK",
    currency: "GBP",
    currencySymbol: "£",
    timezone: "GMT",
    minRate: 1800,
    avgSalary: 110000,
    overheadCost: 30000,
    hiringDifficulty: "High",
  },
  {
    slug: "new-york",
    city: "New York",
    country: "USA",
    flag: "🇺🇸",
    region: "North America",
    currency: "USD",
    currencySymbol: "$",
    timezone: "EST",
    minRate: 2500,
    avgSalary: 185000,
    overheadCost: 45000,
    hiringDifficulty: "Extremely High",
  },
  {
    slug: "toronto",
    city: "Toronto",
    country: "Canada",
    flag: "🇨🇦",
    region: "North America",
    currency: "CAD",
    currencySymbol: "$",
    timezone: "EST",
    minRate: 3000,
    avgSalary: 145000,
    overheadCost: 35000,
    hiringDifficulty: "High",
  },
  {
    slug: "sydney",
    city: "Sydney",
    country: "Australia",
    flag: "🇦🇺",
    region: "Oceania",
    currency: "AUD",
    currencySymbol: "$",
    timezone: "AEST",
    minRate: 3500,
    avgSalary: 165000,
    overheadCost: 40000,
    hiringDifficulty: "High",
  },
  {
    slug: "amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    flag: "🇳🇱",
    region: "Europe",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "CET",
    minRate: 2000,
    avgSalary: 90000,
    overheadCost: 22000,
    hiringDifficulty: "Medium",
  },
  {
    slug: "dubai",
    city: "Dubai",
    country: "UAE",
    flag: "🇦🇪",
    region: "Middle East",
    currency: "AED",
    currencySymbol: "AED",
    timezone: "GST",
    minRate: 8000,
    avgSalary: 380000,
    overheadCost: 0, // Tax free, but high relocation/visa
    hiringDifficulty: "High",
  },
  {
    slug: "frankfurt",
    city: "Frankfurt",
    country: "Germany",
    flag: "🇩🇪",
    region: "Europe",
    currency: "EUR",
    currencySymbol: "€",
    timezone: "CET",
    minRate: 2500,
    avgSalary: 105000,
    overheadCost: 28000,
    hiringDifficulty: "High",
  },
  {
    slug: "san-francisco",
    city: "San Francisco",
    country: "USA",
    flag: "🇺🇸",
    region: "North America",
    currency: "USD",
    currencySymbol: "$",
    timezone: "PST",
    minRate: 3000,
    avgSalary: 210000,
    overheadCost: 55000,
    hiringDifficulty: "Extremely High",
  },
  {
    slug: "melbourne",
    city: "Melbourne",
    country: "Australia",
    flag: "🇦🇺",
    region: "Oceania",
    currency: "AUD",
    currencySymbol: "$",
    timezone: "AEST",
    minRate: 3500,
    avgSalary: 160000,
    overheadCost: 38000,
    hiringDifficulty: "High",
  }
];
